### ISSUE TITLE
Dedupe for Memory

### ISSUE THREAD

**Issue by ThoRyder** [mistic100/Rainmeter-TopProcesses#5]
Should the Dedupe work when the MetricType is Memory?  Documentation is somewhat incomplete, as it shows an example where it is used for CPU, but doesn't mention whether it should do the same for Memory.  Asking because I'm *not* seeing Dedupe work for the Memory measures.
Cheers.

**Comment by mistic100** [comment]
Yes the Dedupe is applied at query level so on all measures.

https://github.com/mistic100/Rainmeter-TopProcesses/blob/ab877aa601c386da710dad822a04453869541389/DataThread.cs#L164-L180

You should post an screenshot....

**Comment by ThoRyder** [comment]
Hi, mistic.  Thanks for the response.  Attached is a screenshot where there are multiple "msedge*" and "chrome*" processes, along with a clip of the INI file code segment.  Maybe I don't have something defined correctly in the INI file?
Cheers.
![Rainmeter_TopProcesses_Dedupe1](https://github.com/mistic100/Rainmeter-TopProcesses/assets/147479470/c71d873c-fcac-4493-92aa-197a838e038f)
![Rainmeter_TopProcesses_Dedupe2](https://github.com/mistic100/Rainmeter-TopProcesses/assets/147479470/6d4b2dde-e835-450b-b0ed-2b99b75e562e)

**Comment by mistic100** [comment]
You must have only one measure with ReQuery=1 as stated in the README and it will be the one with Dedupe=1 (which is the default actually)

**Comment by ThoRyder** [comment]
So this is the entirety of the code segment I've been using to get both top CPU and RAM processes.  I've just tried a number of combinations of excluding the ReQuery/Dedupe lines from the four measures, and none seem to work correctly.  (Quite a few combinations result in blank lines of nothing at all being shown.)  What are you suggesting the actual application of ReQuery/Dedupe ought to be in order to get both similar processes for CPU and RAM to combine and show only once?
Cheers.
![Rainmeter_TopProcesses_Dedupe3](https://github.com/mistic100/Rainmeter-TopProcesses/assets/147479470/71c2e58c-76ca-4a86-be2c-f0592803b0f4)

**Comment by mistic100** [comment]
you should copy paste-code instead of screenshots !

---

I suggest you put ReQuery=1 on the first measure and remove it from all others. and remove Dedupe=1 from all measures.

If that does not work then I am sorry I have no answer for you, in my system it works as expected, I cannot debug more.
